[Feature] 할당하고 싶은 모델만 선택하여 `Bako` 서비스에 추가
kms7530/Salsa pull request #31
Opened 2024-10-15 06:50 UTC by elan1537

2024-10-23 01:30 UTC, kms7530 reviewed
커멘트에 대해 답변 부탁드립니다. 수고 많으셨습니다. :)

2024-10-23 01:30 UTC, kms7530 commented on parser/code_parser.py
각 함수에 인자 타입 힌트가 없습니다.

2024-10-23 01:30 UTC, kms7530 commented on parser/README.md
작성된 내용대로만 따라했을때 동작 확인을 하신건가요?

2024-10-23 01:30 UTC, kms7530 commented on models/vision_language.py
최근에 업로드된 `VisionLanguage` class 그대로 쓰신건가요?

2024-10-23 01:44 UTC, elan1537 commented on models/vision_language.py
네 그대로 가져왔습니다

2024-10-23 01:52 UTC, elan1537 commented on parser/code_parser.py
반영하겠습니다

2024-10-23 01:53 UTC, elan1537 commented on parser/README.md
네. 위 방법대로 적용하면 정상적으로 동작합니다

2024-10-23 02:01 UTC, kms7530 approved these changes
다음 PR에서 추가 반영 내용 확인하겠습니다.

2024-10-23 07:34 UTC, kms7530 commented
#36 확인 부탁드립니다.

2024-10-24 05:11 UTC, kms7530 requested changes
확인 부탁드립니다.

2024-10-24 05:11 UTC, kms7530 commented on parser/code_generator.py
> +def main(args):
타입 힌트가 필요합니다.

2024-10-24 05:11 UTC, kms7530 commented on parser/code_parser.py
타입 힌트가 필요합니다.

2024-10-24 05:15 UTC, kms7530 commented
추가로 최상위 `README.md`에 내용 추가하신다는게 누락되어 있습니다.

2024-10-24 05:22 UTC, elan1537 commented on parser/code_generator.py
> +def main(args):
확인했습니다

2024-10-24 05:23 UTC, elan1537 commented on parser/code_parser.py
Main 말하는 거죠?

2024-10-24 05:25 UTC, kms7530 commented on parser/code_parser.py
소스 전체를 말씀드리는건데, decorator나 class_node는 따로 타입이 없나요?

2024-10-24 05:49 UTC, elan1537 commented on parser/code_parser.py
ast 객체에요. ast.FunctionDef, ast.Call 등이 들어갈 수 있죠

2024-10-24 05:50 UTC, elan1537 commented
> 추가로 최상위 `README.md`에 내용 추가하신다는게 누락되어 있습니다.

Main에 통합 후 작업으로 생각하고 있습니다.

2024-10-24 05:51 UTC, kms7530 commented on parser/code_parser.py
그럼 각자 인자에 맞게 객체 할당 부탁드립니다.

2024-10-24 06:06 UTC, kms7530 reviewed
이전과 비교하여 코드 변경이 많은데, 다 확인되신건가요?
또한, `service.py`에 충돌 확인 부탁드립니다.

2024-10-24 06:15 UTC, elan1537 commented
> 이전과 비교하여 코드 변경이 많은데, 다 확인되신건가요?

지수님 코드에 config_template로 기입되어있는 부분, models가 분리되면서 임포트하는 부분들을 rebase 했습니다. 이전 코드에서 충돌나는 부분이 있어서 그 수정부분 반영한 기존 코드입니다.

서비스 코드는 삭제가 되어야 하기에, merge가 되면서 해소 될 예정입니다.

2024-10-24 06:16 UTC, kms7530 commented
답변 감사드립니다.

2024-10-24 06:16 UTC, kms7530 approved these changes

2024-10-24 06:17 UTC, elan1537 commented
Merge 하겠습니다

2024-10-24 06:22 UTC, merged